In [7]:
import numpy as np
import timeit as ti
size_of_vec = 1000

def py_version():
    A, B = range(size_of_vec), range(size_of_vec)
    C = []
    for i in range(size_of_vec):
        C.append(A[i] + B[i])

def np_version():
    A, B = np.arange(size_of_vec), np.arange(size_of_vec)
    C = A+B

t_py = ti.timeit('py_version()', setup='from __main__ import py_version', number=100)
t_np = ti.timeit('np_version()', setup='from __main__ import np_version', number=100)

print(f'python version : {t_py*100:8.3f}[ms]')
print(f'numpy  version : {t_np*100:8.3f}[ms]')
print(f'numpy is {t_py / t_np:5.1f} times faster than pure python')

python version :    2.058[ms]
numpy  version :    0.072[ms]
numpy is  28.6 times faster than pure python


In [19]:
# 배열의 생성 array(Data) 메서드 사용함.
# data : 수치형 , 리스트, 튜플 등의 파이썬 자료형 데이터

x= np.array(43)
# 0차원의 데이터
print(np.ndim(x))

0


In [23]:
# 1차원abs
F = np.array([1,2,3,4,5])
print(F.dtype)
print(np.ndim(F))

int64
1


In [25]:
# 리스트로 다차원 배열 만들기abs
B = np.array([ [[111, 112], [121, 122]],
[[211, 212], [221, 222]],
[[311, 312], [321, 322]] ])
print(B)
print(B.ndim)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
3


In [31]:
# arange 함수 : 내장함수 Range와 다르게 float형도 가능함.abs
ary = np.arange(0, 1.1, 0.5, np.float32)
print(ary)

[0.  0.5 1. ]


In [35]:
# linspace 메서드 : 주어진 범위에서 원하는 개수만큼 등간격 1차원 배열을 생성한다.abs
print(np.linspace(1, 10, 7))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]


In [37]:
a=np.array(99)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4]]) # 행벡터
d=np.array([[1],[2],[3],[4]]) # 열벡터
print(f'{a} shape: {a.shape} dim: {a.ndim}')
print(f'{b} shape: {b.shape} dim: {b.ndim}')
print(f'{c} shape: {c.shape} dim: {c.ndim}')
print(f'{d} shape: {d.shape} dim: {d.ndim}')

99 shape: () dim: 0
[1 2 3 4] shape: (4,) dim: 1
[[1 2 3 4]] shape: (1, 4) dim: 2
[[1]
 [2]
 [3]
 [4]] shape: (4, 1) dim: 2


In [39]:
x = np.array([[11,12,13] , [21,22,23], [31, 32, 33], [41, 42, 43], [51,52,53], [61, 62, 63]])
x.shape = (3,6)

In [43]:
print(x)
# reshape을 할 때는 전체 원소수가 맞아야 함.

[[11 12 13 21 22 23]
 [31 32 33 41 42 43]
 [51 52 53 61 62 63]]


In [2]:
import numpy as np
data = np.random.rand(3,3)
print(data)

[[0.76868591 0.34575991 0.87575525]
 [0.25878404 0.04934914 0.79962609]
 [0.11818111 0.90569939 0.7508194 ]]


In [8]:
print(data > 0.5)
print(data[data > 0.5])
data[data > 0.5] = 0
print(data)

[[ True False  True]
 [False False  True]
 [False  True  True]]
[0.76868591 0.87575525 0.79962609 0.90569939 0.7508194 ]
[[0.         0.34575991 0.        ]
 [0.25878404 0.04934914 0.        ]
 [0.11818111 0.         0.        ]]


In [ ]:
# 배열에 수치형 값을 넣으면 모든 원소가 바뀌는데 이를 브로드 캐스팅이라고 함.


In [14]:
# 배열의 슬라이싱

A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55],
])
A[3:, 4:]
A[:, 4:]
             

array([[15],
       [25],
       [35],
       [45],
       [55]])

In [16]:
B = np.array([ [[111, 112], [121, 122]],
[[211, 212], [221, 222]],
[[311, 312], [321, 322]] ])
print(B[0, ...])

[[111 112]
 [121 122]]


In [24]:
a = np.arange(2*3*4)
print(a)
t = a.reshape(3, 2, 4)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [32]:
A = np.arange(28).reshape(7,-1)

In [34]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [ ]:
import matplotlib.pyplot as plt
v = np.array([[0,0], [10,0], [0,10]])
v = np.vstack(v, v[0, :])
d = np.vstack             